const gemstonesData = {
  "gemstones": [
    {
      "id": 1,
      "name": "Amethyst",
      "color": "Purple to violet",
      "hardness": 7,
      "crystal_system": "Trigonal",
      "chemical_formula": "SiO₂",
      "transparency": "Transparent to translucent",
      "luster": "Vitreous",
      "chakra": "Crown, Third Eye",
      "zodiac": "Pisces, Virgo, Aquarius, Capricorn",
      "element": "Air, Water",
      "spiritual_properties": "Calming, spiritual awareness, meditation, protection from negative energy, sobriety, emotional balance",
      "physical_healing": "Headaches, insomnia, stress relief, immune system support",
      "trivia": "The name comes from the Greek 'amethystos' meaning 'not intoxicated' - ancient Greeks believed it prevented drunkenness.",
      "image_url": "images/amethyst.jpg"
    },
    {
      "id": 2,
      "name": "Rose Quartz",
      "color": "Pink to rose red",
      "hardness": 7,
      "crystal_system": "Trigonal",
      "chemical_formula": "SiO₂",
      "transparency": "Translucent",
      "luster": "Vitreous",
      "chakra": "Heart",
      "zodiac": "Taurus, Libra",
      "element": "Water, Earth",
      "spiritual_properties": "Unconditional love, compassion, emotional healing, self-love, forgiveness, peace",
      "physical_healing": "Heart health, circulation, skin rejuvenation, fertility",
      "trivia": "Rose quartz is often called the 'Stone of Universal Love' and has been used in love rituals since 600 B.C.",
      "image_url": "images/rose_quartz.jpg"
    },
    {
      "id": 3,
      "name": "Clear Quartz",
      "color": "Colorless, white",
      "hardness": 7,
      "crystal_system": "Trigonal",
      "chemical_formula": "SiO₂",
      "transparency": "Transparent",
      "luster": "Vitreous",
      "chakra": "All (Crown primarily)",
      "zodiac": "All signs",
      "element": "All elements",
      "spiritual_properties": "Amplification, clarity, energy enhancement, manifestation, spiritual growth, cleanses other crystals",
      "physical_healing": "General healing, immune system boost, pain relief, energy balance",
      "trivia": "Known as the 'Master Healer' and can be programmed with intentions. Used in watches and electronics for its piezoelectric properties.",
      "image_url": "images/clear_quartz.jpg"
    },
    {
      "id": 4,
      "name": "Citrine",
      "color": "Yellow to golden brown",
      "hardness": 7,
      "crystal_system": "Trigonal",
      "chemical_formula": "SiO₂",
      "transparency": "Transparent to translucent",
      "luster": "Vitreous",
      "chakra": "Solar Plexus, Sacral",
      "zodiac": "Aries, Gemini, Leo, Libra",
      "element": "Fire",
      "spiritual_properties": "Abundance, prosperity, success, confidence, creativity, joy, manifestation of wealth",
      "physical_healing": "Digestion, metabolism, energy boost, detoxification",
      "trivia": "Called the 'Merchant's Stone' or 'Success Stone' - often placed in cash registers to attract wealth. Most citrine is actually heat-treated amethyst.",
      "image_url": "images/citrine.webp"
    },
    {
      "id": 5,
      "name": "Black Tourmaline",
      "color": "Black, opaque",
      "hardness": 7.5,
      "crystal_system": "Trigonal",
      "chemical_formula": "Complex borosilicate",
      "transparency": "Opaque",
      "luster": "Vitreous to resinous",
      "chakra": "Root",
      "zodiac": "Capricorn",
      "element": "Earth",
      "spiritual_properties": "Protection, grounding, EMF protection, removes negative energy, psychic shielding, anxiety relief",
      "physical_healing": "Pain relief, immune system, detoxification, arthritis",
      "trivia": "Tourmaline is pyroelectric - it becomes electrically charged when heated. Used in pressure gauges and as a gemstone since ancient times.",
      "image_url": "images/black_tourmaline.webp"
    },
    {
      "id": 6,
      "name": "Lapis Lazuli",
      "color": "Deep blue with golden pyrite flecks",
      "hardness": 5.5,
      "crystal_system": "Aggregate (not single crystal)",
      "chemical_formula": "Complex (lazurite, calcite, pyrite)",
      "transparency": "Opaque",
      "luster": "Dull to vitreous",
      "chakra": "Third Eye, Throat",
      "zodiac": "Sagittarius, Libra",
      "element": "Water",
      "spiritual_properties": "Wisdom, truth, spiritual enlightenment, communication, intuition, inner vision, self-awareness",
      "physical_healing": "Throat issues, immune system, insomnia, blood pressure",
      "trivia": "Prized since antiquity - used in Egyptian burial masks, including King Tut's. Ground lapis was used to make ultramarine pigment in Renaissance paintings.",
      "image_url": "images/lapis_lazuli.webp"
    },
    {
      "id": 7,
      "name": "Selenite",
      "color": "Colorless, white, peach",
      "hardness": 2,
      "crystal_system": "Monoclinic",
      "chemical_formula": "CaSO₄·2H₂O",
      "transparency": "Transparent to translucent",
      "luster": "Pearly, silky",
      "chakra": "Crown, Third Eye",
      "zodiac": "Taurus",
      "element": "Air",
      "spiritual_properties": "Cleansing, clarity, spiritual activation, angelic communication, mental clarity, cleanses other crystals",
      "physical_healing": "Spine alignment, flexibility, epilepsy, muscle tension",
      "trivia": "Named after Selene, Greek goddess of the moon. So soft it can be scratched with a fingernail. Should never be placed in water as it will dissolve.",
      "image_url": "images/selenite.jpg"
    },
    {
      "id": 8,
      "name": "Carnelian",
      "color": "Orange to red-brown",
      "hardness": 7,
      "crystal_system": "Trigonal",
      "chemical_formula": "SiO₂",
      "transparency": "Translucent",
      "luster": "Vitreous",
      "chakra": "Sacral, Root",
      "zodiac": "Virgo, Leo, Taurus",
      "element": "Fire",
      "spiritual_properties": "Courage, motivation, creativity, vitality, confidence, passion, overcoming abuse",
      "physical_healing": "Fertility, sexuality, lower back pain, rheumatism, kidney function",
      "trivia": "Ancient Egyptians called it 'the setting sun' and used it in jewelry and amulets. Warriors wore it for courage in battle.",
      "image_url": "images/carnelian.jpg"
    },
    {
      "id": 9,
      "name": "Malachite",
      "color": "Green with banding patterns",
      "hardness": 3.5,
      "crystal_system": "Monoclinic",
      "chemical_formula": "Cu₂CO₃(OH)₂",
      "transparency": "Opaque",
      "luster": "Silky to dull",
      "chakra": "Heart, Throat",
      "zodiac": "Scorpio, Capricorn",
      "element": "Earth",
      "spiritual_properties": "Transformation, protection, risk-taking, emotional healing, breaking unwanted patterns, willpower",
      "physical_healing": "Pain relief, childbirth, immune system, menstrual cramps, blood pressure",
      "trivia": "Highly toxic when in dust/powder form - should not be used in direct elixirs. The distinctive banding pattern makes each piece unique.",
      "image_url": "images/malachite.webp"
    },
    {
      "id": 10,
      "name": "Moonstone",
      "color": "White with blue sheen (adularescence)",
      "hardness": 6,
      "crystal_system": "Monoclinic",
      "chemical_formula": "KAlSi₃O₈",
      "transparency": "Transparent to translucent",
      "luster": "Vitreous",
      "chakra": "Crown, Third Eye, Heart",
      "zodiac": "Cancer, Libra, Scorpio",
      "element": "Water",
      "spiritual_properties": "Intuition, feminine energy, emotional balance, new beginnings, inner growth, lunar connection",
      "physical_healing": "Hormonal balance, PMS, fertility, childbirth, digestive system",
      "trivia": "The shimmering effect is caused by light scattering between microscopic layers of feldspar. Sacred in India and considered a dream stone.",
      "image_url": "images/moonstone.jpg"
    },
    {
      "id": 11,
      "name": "Labradorite",
      "color": "Gray with colorful iridescence (labradorescence)",
      "hardness": 6.5,
      "crystal_system": "Triclinic",
      "chemical_formula": "(Ca,Na)(Al,Si)₄O₈",
      "transparency": "Translucent to opaque",
      "luster": "Vitreous",
      "chakra": "Third Eye, Crown, Throat",
      "zodiac": "Leo, Scorpio, Sagittarius",
      "element": "Water, Air",
      "spiritual_properties": "Transformation, magic, psychic abilities, protection, intuition, synchronicity, inner worth",
      "physical_healing": "Eye and brain health, anxiety, digestion, metabolism",
      "trivia": "Named after Labrador, Canada where it was discovered. Inuit legend says the Northern Lights were trapped in rocks along the coast.",
      "image_url": "images/labradorite.webp"
    },
    {
      "id": 12,
      "name": "Tiger's Eye",
      "color": "Golden brown with chatoyancy (cat's eye effect)",
      "hardness": 7,
      "crystal_system": "Trigonal",
      "chemical_formula": "SiO₂",
      "transparency": "Opaque",
      "luster": "Silky",
      "chakra": "Solar Plexus, Sacral, Root",
      "zodiac": "Capricorn, Leo",
      "element": "Fire, Earth",
      "spiritual_properties": "Confidence, courage, willpower, grounding, protection, practical decision-making, personal power",
      "physical_healing": "Eye health, bones, joints, digestive system, anxiety relief",
      "trivia": "Roman soldiers wore it for protection in battle. The chatoyant effect is caused by fibrous structure that reflects light in bands.",
      "image_url": "images/tigers_eye.webp"
    },
    {
      "id": 13,
      "name": "Hematite",
      "color": "Metallic gray to black (red streak)",
      "hardness": 6.5,
      "crystal_system": "Trigonal",
      "chemical_formula": "Fe₂O₃",
      "transparency": "Opaque",
      "luster": "Metallic",
      "chakra": "Root",
      "zodiac": "Aries, Aquarius",
      "element": "Earth",
      "spiritual_properties": "Grounding, protection, focus, concentration, dissolves negativity, courage, legal issues",
      "physical_healing": "Blood disorders, circulation, leg cramps, anxiety, insomnia",
      "trivia": "The name comes from Greek 'haima' (blood) because it produces a red streak when scratched. Ancient warriors rubbed it on their bodies for invincibility.",
      "image_url": "images/hematite.jpg"
    },
    {
      "id": 14,
      "name": "Jade (Jadeite)",
      "color": "Green (also white, lavender, red, yellow)",
      "hardness": 6.5,
      "crystal_system": "Monoclinic",
      "chemical_formula": "NaAlSi₂O₆",
      "transparency": "Translucent to opaque",
      "luster": "Vitreous to greasy",
      "chakra": "Heart",
      "zodiac": "Aries, Taurus, Gemini, Libra",
      "element": "Earth",
      "spiritual_properties": "Harmony, luck, prosperity, wisdom, peace, longevity, protection, dream recall",
      "physical_healing": "Kidney function, adrenal glands, bones, joints, detoxification",
      "trivia": "Prized in Chinese culture for over 5,000 years. True jade is either jadeite or nephrite - other 'jades' are usually serpentine.",
      "image_url": "images/jade.png"
    },
    {
      "id": 15,
      "name": "Obsidian",
      "color": "Black (also rainbow, snowflake, mahogany)",
      "hardness": 5.5,
      "crystal_system": "Amorphous (volcanic glass)",
      "chemical_formula": "SiO₂ (variable composition)",
      "transparency": "Translucent to opaque",
      "luster": "Vitreous",
      "chakra": "Root",
      "zodiac": "Sagittarius, Scorpio",
      "element": "Earth, Fire",
      "spiritual_properties": "Protection, grounding, truth, deep soul healing, reveals shadow self, psychic cleansing",
      "physical_healing": "Digestion, detoxification, pain relief, circulation",
      "trivia": "Formed when lava cools rapidly without crystal growth. Used for tools and weapons by ancient civilizations - sharper than surgical steel.",
      "image_url": "images/obsidian_2.webp"
    },
    {
      "id": 16,
      "name": "Turquoise",
      "color": "Blue to green, often with veining",
      "hardness": 6,
      "crystal_system": "Triclinic",
      "chemical_formula": "CuAl₆(PO₄)₄(OH)₈·4H₂O",
      "transparency": "Opaque",
      "luster": "Waxy to dull",
      "chakra": "Throat, Third Eye, Heart",
      "zodiac": "Sagittarius, Pisces, Scorpio",
      "element": "Earth, Air",
      "spiritual_properties": "Communication, wisdom, protection, good fortune, friendship, healing, purification",
      "physical_healing": "Immune system, anti-inflammatory, detoxification, pain relief, respiratory issues",
      "trivia": "One of the oldest gemstones known - worn by Egyptian pharaohs and Native American tribes. Supposedly changes color to warn of danger.",
      "image_url": "images/turquoise.jpg"
    },
    {
      "id": 17,
      "name": "Fluorite",
      "color": "Purple, green, blue, yellow, clear (often banded)",
      "hardness": 4,
      "crystal_system": "Isometric",
      "chemical_formula": "CaF₂",
      "transparency": "Transparent to translucent",
      "luster": "Vitreous",
      "chakra": "Third Eye, Crown, Heart (varies by color)",
      "zodiac": "Pisces, Capricorn",
      "element": "Air, Water",
      "spiritual_properties": "Mental clarity, focus, decision-making, learning, intuition, cleanses aura, electromagnetic protection",
      "physical_healing": "Bone health, dental issues, joint pain, virus protection",
      "trivia": "Fluoresces under UV light (the term 'fluorescence' is named after fluorite). Ancient Romans believed drinking from fluorite cups prevented drunkenobsidian.",
      "image_url": "images/fluorite.jpg"
    },
    {
      "id": 18,
      "name": "Aventurine",
      "color": "Green (also blue, orange, brown)",
      "hardness": 7,
      "crystal_system": "Trigonal",
      "chemical_formula": "SiO₂",
      "transparency": "Translucent to opaque",
      "luster": "Vitreous",
      "chakra": "Heart",
      "zodiac": "Aries, Leo",
      "element": "Earth, Water",
      "spiritual_properties": "Luck, prosperity, opportunity, optimism, confidence, perseverance, leadership",
      "physical_healing": "Heart health, cholesterol, allergies, skin issues, eye health",
      "trivia": "Called the 'Stone of Opportunity' and considered luckiest of all crystals for manifesting prosperity. The sparkle comes from mica inclusions.",
      "image_url": "images/aventurine.jpg"
    },
    {
      "id": 19,
      "name": "Sodalite",
      "color": "Blue with white calcite veining",
      "hardness": 5.5,
      "crystal_system": "Isometric",
      "chemical_formula": "Na₈Al₆Si₆O₂₄Cl₂",
      "transparency": "Translucent to opaque",
      "luster": "Vitreous to greasy",
      "chakra": "Throat, Third Eye",
      "zodiac": "Sagittarius",
      "element": "Water, Air",
      "spiritual_properties": "Logic, truth, intuition, communication, emotional balance, panic relief, self-acceptance",
      "physical_healing": "Throat issues, vocal cords, blood pressure, insomnia, metabolism",
      "trivia": "Often confused with lapis lazuli but lacks the pyrite flecks. Named for its high sodium content. Used in the Canadian Parliament buildings.",
      "image_url": "images/sodalite.jpg"
    },
    {
      "id": 20,
      "name": "Garnet",
      "color": "Deep red (also green, orange, pink)",
      "hardness": 7.5,
      "crystal_system": "Isometric",
      "chemical_formula": "Complex silicate (varies)",
      "transparency": "Transparent to translucent",
      "luster": "Vitreous",
      "chakra": "Root, Heart",
      "zodiac": "Capricorn, Aquarius, Leo",
      "element": "Fire, Earth",
      "spiritual_properties": "Passion, energy, commitment, regeneration, balance, protection during travel, manifestation",
      "physical_healing": "Blood circulation, heart health, metabolism, libido, cellular regeneration",
      "trivia": "The name comes from Latin 'granatum' (pomegranate seed). Noah's Ark supposedly used a garnet lantern for light. January birthstone.",
      "image_url": "images/garnet.jpg"
    },
    {
      "id": 21,
      "name": "Pyrite",
      "color": "Metallic gold",
      "hardness": 6.5,
      "crystal_system": "Isometric",
      "chemical_formula": "FeS₂",
      "transparency": "Opaque",
      "luster": "Metallic",
      "chakra": "Solar Plexus",
      "zodiac": "Leo",
      "element": "Fire, Earth",
      "spiritual_properties": "Manifestation, action, willpower, protection, confidence, memory, vitality, shields from negative energy",
      "physical_healing": "Circulation, lungs, digestion, bone structure, DNA repair",
      "trivia": "Known as 'Fool's Gold' but was used to start fires in ancient times by striking it against metal. The name comes from Greek 'pyr' meaning fire.",
      "image_url": "images/pyrite.webp"
    },
    {
      "id": 22,
      "name": "Aquamarine",
      "color": "Light blue to blue-green",
      "hardness": 7.5,
      "crystal_system": "Hexagonal",
      "chemical_formula": "Be₃Al₂Si₆O₁₈",
      "transparency": "Transparent to translucent",
      "luster": "Vitreous",
      "chakra": "Throat, Heart",
      "zodiac": "Pisces, Aries, Gemini",
      "element": "Water",
      "spiritual_properties": "Courage, communication, calming, flow, release, tolerance, clarity, protection for travelers",
      "physical_healing": "Throat issues, allergies, immune system, thyroid, eyes, teeth",
      "trivia": "Name means 'water of the sea' in Latin. Sailors carried it as a talisman against drowning. Part of the beryl family (same as emerald).",
      "image_url": "images/aquamarine.webp"
    },
    {
      "id": 23,
      "name": "Smoky Quartz",
      "color": "Brown to black smoky translucent",
      "hardness": 7,
      "crystal_system": "Trigonal",
      "chemical_formula": "SiO₂",
      "transparency": "Transparent to translucent",
      "luster": "Vitreous",
      "chakra": "Root",
      "zodiac": "Scorpio, Sagittarius, Capricorn",
      "element": "Earth",
      "spiritual_properties": "Grounding, removes negative energy, stress relief, protection, practical thinking, emotional calmness",
      "physical_healing": "Detoxification, pain relief, muscle tension, reproductive system, radiation protection",
      "trivia": "The smoky color is caused by natural radiation exposure over millions of years. National gemstone of Scotland and used in Celtic jewelry.",
      "image_url": "images/smoky_quartz.webp"
    },
    {
      "id": 24,
      "name": "Amazonite",
      "color": "Green to blue-green",
      "hardness": 6.5,
      "crystal_system": "Triclinic",
      "chemical_formula": "KAlSi₃O₈",
      "transparency": "Translucent to opaque",
      "luster": "Vitreous",
      "chakra": "Heart, Throat",
      "zodiac": "Virgo",
      "element": "Water, Earth",
      "spiritual_properties": "Truth, communication, harmony, soothing worry, balance, manifestation, personal boundaries",
      "physical_healing": "Osteoporosis, tooth decay, muscle spasms, nervous system, EMF protection",
      "trivia": "Named after the Amazon River though not found there. The green color comes from lead impurities. Found in ancient Egyptian and Mesopotamian jewelry.",
      "image_url": "images/amazonite.jpg"
    },
    {
      "id": 25,
      "name": "Rhodonite",
      "color": "Pink to red with black manganese veins",
      "hardness": 6,
      "crystal_system": "Triclinic",
      "chemical_formula": "MnSiO₃",
      "transparency": "Translucent to opaque",
      "luster": "Vitreous to pearly",
      "chakra": "Heart, Root",
      "zodiac": "Taurus",
      "element": "Earth, Fire",
      "spiritual_properties": "Emotional healing, forgiveness, compassion, discovering hidden talents, self-love, confidence",
      "physical_healing": "Heart health, arthritis, bone growth, hearing, immunity",
      "trivia": "Name comes from Greek 'rhodon' meaning rose. Russian czars favored it and it was used extensively in Russian decorative arts.",
      "image_url": "images/rhodonite.png"
    },
    {
      "id": 26,
      "name": "Bloodstone",
      "color": "Dark green with red spots",
      "hardness": 7,
      "crystal_system": "Trigonal",
      "chemical_formula": "SiO₂",
      "transparency": "Opaque",
      "luster": "Vitreous",
      "chakra": "Root, Heart",
      "zodiac": "Aries, Pisces",
      "element": "Earth",
      "spiritual_properties": "Courage, strength, vitality, grounding, purification, protection, decision-making, survival instincts",
      "physical_healing": "Blood circulation, anemia, detoxification, immune system, childbirth",
      "trivia": "Also called 'heliotrope'. Medieval legend says the red spots formed from Christ's blood at the crucifixion. Warriors wore it to stop bleeding.",
      "image_url": "images/bloodstone.webp"
    },
    {
      "id": 27,
      "name": "Lepidolite",
      "color": "Pink to purple with mica shimmer",
      "hardness": 2.5,
      "crystal_system": "Monoclinic",
      "chemical_formula": "K(Li,Al)₃(Al,Si,Rb)₄O₁₀(F,OH)₂",
      "transparency": "Translucent to opaque",
      "luster": "Pearly",
      "chakra": "Heart, Third Eye, Crown",
      "zodiac": "Libra",
      "element": "Water",
      "spiritual_properties": "Calm, emotional balance, stress relief, transition, awareness, cosmic connection, independence",
      "physical_healing": "Sleep disorders, anxiety, depression, bipolar disorder, menopause, nerve pain",
      "trivia": "Contains lithium - the same element used in mood-stabilizing medications. Often found with pink tourmaline. Name means 'scale stone' due to its flaky structure.",
      "image_url": "images/lepidolite.jpg"
    },
    {
      "id": 28,
      "name": "Sunstone",
      "color": "Orange to red with glittery effect",
      "hardness": 6.5,
      "crystal_system": "Triclinic",
      "chemical_formula": "(Ca,Na)(Al,Si)₄O₈",
      "transparency": "Transparent to translucent",
      "luster": "Vitreous",
      "chakra": "Sacral, Solar Plexus",
      "zodiac": "Leo, Libra",
      "element": "Fire",
      "spiritual_properties": "Joy, vitality, independence, originality, good luck, personal power, leadership, freedom",
      "physical_healing": "Metabolism, digestion, sore throat, cartilage, spine, seasonal affective disorder",
      "trivia": "The sparkle (aventurescence) comes from copper or hematite inclusions. Oregon sunstone is the official state gemstone of Oregon.",
      "image_url": "images/sunstone.webp"
    },
    {
      "id": 29,
      "name": "Chrysocolla",
      "color": "Blue-green to turquoise",
      "hardness": 2.5,
      "crystal_system": "Orthorhombic (usually amorphous)",
      "chemical_formula": "(Cu,Al)₂H₂Si₂O₅(OH)₄·nH₂O",
      "transparency": "Translucent to opaque",
      "luster": "Vitreous to greasy",
      "chakra": "Throat, Heart",
      "zodiac": "Taurus, Gemini, Virgo",
      "element": "Water",
      "spiritual_properties": "Communication, teaching, empowerment of feminine energies, peace, tranquility, meditation, acceptance",
      "physical_healing": "Thyroid, metabolism, menstrual cramps, arthritis, muscle tension, blood disorders",
      "trivia": "Name means 'gold glue' in Greek - used to solder gold in ancient times. Cleopatra allegedly carried it everywhere for its calming properties.",
      "image_url": "images/chrysocolla.jpg"
    },
    {
      "id": 30,
      "name": "Azurite",
      "color": "Deep blue",
      "hardness": 3.5,
      "crystal_system": "Monoclinic",
      "chemical_formula": "Cu₃(CO₃)₂(OH)₂",
      "transparency": "Translucent to opaque",
      "luster": "Vitreous",
      "chakra": "Third Eye, Throat",
      "zodiac": "Sagittarius",
      "element": "Water",
      "spiritual_properties": "Psychic abilities, intuition, spiritual wisdom, releasing old beliefs, inner vision, meditation",
      "physical_healing": "Throat issues, arthritis, joint pain, spine alignment, skin disorders",
      "trivia": "Ground into powder, it created a brilliant blue pigment used by Renaissance painters. Transforms into malachite over time when exposed to moisture.",
      "image_url": "images/azurite.webp"
    }
  ],
  "metadata": {
    "version": "1.0",
    "total_gemstones": 30,
    "last_updated": "2026-02-12",
    "note": "Image URLs are placeholders - replace with your actual image paths or use the Kaggle gemstone dataset for images"
  }
}




